# Generated by Django 4.2.5 on 2023-09-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_alter_comment_options_remove_comment_active'),
        ('Blog', '0008_profile_profile_picture'),
    ]

    operations = [
    ]
