# Generated by Django 4.2.5 on 2023-11-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_rename_photo_post_post_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_photo',
        ),
    ]
