# Generated by Django 4.2.5 on 2023-11-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='posted_by', to='Blog.post'),
        ),
    ]
