# Generated by Django 4.2.5 on 2023-11-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0017_profile_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='posts',
        ),
    ]
